repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.30.0
    hooks:
      - id: yapf

  - repo: local
    hooks:
      - id: tests
        name: run tests
        entry: pytest
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
      - id: isort
        name: sort imports
        entry: pytest
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
